# Generated by Django 4.1.3 on 2023-05-25 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instabam', '0002_customuser_repost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
