# Generated by Django 4.1.3 on 2023-05-27 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instabam', '0005_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='body',
        ),
    ]
