# Generated by Django 4.1.3 on 2023-05-27 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instabam', '0006_remove_reply_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='repost',
            name='caption_text',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
