# Generated by Django 4.1.3 on 2023-05-28 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instabam', '0007_repost_caption_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RePost',
        ),
    ]
