# Generated by Django 4.1.3 on 2023-07-31 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instabam', '0009_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
    ]
