# Generated by Django 4.1.3 on 2023-06-07 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instabam', '0010_remove_userprofile_followers_userprofile_follows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='followed_by', to='instabam.userprofile'),
        ),
    ]
