# Generated by Django 4.1.3 on 2023-06-14 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instabam', '0014_likepost'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowersCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_userprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='instabam.userprofile')),
                ('to_userprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='instabam.userprofile')),
            ],
        ),
    ]
