# Generated by Django 4.2.3 on 2023-08-01 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instabam', '0011_alter_post_id_alter_reply_id'),
        ('instabam', '0016_remove_followerscount_from_userprofile_and_more'),
    ]

    operations = [
    ]
